const HOST = 'game.bloque.app';
const PORT = 2812;
const FISH_COMMAND = '/fish\n';
const INVENTORY_COMMAND = '/inventory\n';
const MARKET_COMMAND = '/market\n';
const INVITATION_CODE = 'BLQ-SNF0CINS';
const LONG_WAIT_MIN_SECONDS = 31;
const LONG_WAIT_MAX_SECONDS = 45;

const FISH_DELAY_MS = 400;
const STATUS_INTERVAL_MS = 5 * 60 * 1000; // 5 minutes
const INVENTORY_TRIGGER_COUNT = 10;
const MARKET_TRIGGER_COUNT = 30;
const POISON_TRIGGER_COUNT = 6;

const INVENTORY_INTERVAL = 60000; // Real 5 minuts 300000

const OVERPRICED = 10000;

module.exports = { 
    HOST,
    PORT,
    FISH_COMMAND,
    INVENTORY_COMMAND,
    MARKET_COMMAND,
    INVITATION_CODE,
    LONG_WAIT_MAX_SECONDS,
    LONG_WAIT_MIN_SECONDS,
    FISH_DELAY_MS,
    STATUS_INTERVAL_MS,
    INVENTORY_TRIGGER_COUNT,
    MARKET_TRIGGER_COUNT,
    POISON_TRIGGER_COUNT,
    INVENTORY_INTERVAL,
    OVERPRICED
}